# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20180114_1836'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Підписник', 'verbose_name_plural': 'Підписники'},
        ),
    ]
