# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-08 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='is_active',
            new_name='flag',
        ),
    ]
