# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180208_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
