# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-19 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='syte_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='autrhor',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='flag',
            field=models.BooleanField(default=True, verbose_name='Акт/Деакт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Імя'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Оновлено'),
        ),
    ]
