# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20180219_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('name', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Тип книги')),
                ('flag', models.BooleanField(default=True, verbose_name='Акт/Деакт')),
            ],
            options={
                'verbose_name': 'Тип книги',
                'verbose_name_plural': 'Типи книг',
            },
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='book_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.BookType'),
        ),
    ]
